name: Test test test!

on:
  - push

jobs:
  test:
    name: Unit and Integration Tests

    runs-on: ubuntu-18.04

    steps:
      # checks-out current repo under $GITHUB_WORKSPACE
      - name: Checkout the repo
        uses: actions/checkout@v2

      # install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.10"

      # install deps
      - name: Install dependencies
        run: |
          uv sync --locked --dev

      # run test suite
      - name: Run test suite
        run: |
          uv run -m unittest discover --start-directory Test -v
